idf_component_register(
    SRCS 
    "HTTP_server.c"
    "api/system/config_dispatcher.c"
    "api/system/config/cfg_complete.c"
    "api/system/config/cfg_device_info.c"
    "api/system/config/cfg_ping.c"
    "api/system/config/cfg_diagnostic.c"
    "api/system/config/cfg_reboot.c"
    "api/system/config/cfg_timeout.c"
    "api/system/ota_dispatcher.c"
    "api/system/ota/ota_commit.c"
    "api/system/ota/ota_info.c"
    "api/system/ota/ota_reboot.c"
    "api/system/ota/ota_start.c"
    "api/system/ota/ota_status.c"
    "api/system/ota/ota_upload.c"
    "api/system/wifi_dispatcher.c"
    "api/system/wifi/wifi_credentials.c"
    "api/system/wifi/wifi_connect.c"
    "api/system/wifi/wifi_scan.c"
    "api/system/wifi/wifi_status.c"
    "api/system/wifi/wifi_switch.c"
    "api/ui/screen_dispatcher.c"
    "api/ui/screens.c"
    "api/ui/screens/scr_active.c"
    "api/ui/screens/scr_layout.c"
    "api/ui/screens/scr_refresh.c"
    "api/ui/widgets.c"
    "api/ui/widgets/layout.c"
    "api/ui/widgets/available.c"
    "api/ui/widgets/{name}.c"
    "api/ui/widgets/widgets_dispatcher.c"
    "queue/widget_update.c"
    "utils/json.c"
    "utils/read_http_request_content.c"
    "utils/config_timeout_ctx.c"

    INCLUDE_DIRS 
    "include"

    REQUIRES
    wifi
    filesystem_interface
    esp-tls 
    esp_http_server 
    esp_wifi
    json
    UI
    ota
)
