idf_component_register(
    SRCS 
    "UI.c"
    "init_lvgl.c"
    "draw/qrcode.c"
    "draw/btn_bottom_left.c"
    "draw/btn_bottom_right.c"
    "draw/screen/wifi_config.c"
    "draw/screen/wifi_success.c"
    "draw/screen/splash_screen.c"
    "font/roboto_48.c"
    "font/roboto_64.c"
    "font/roboto_96.c"
    "font/roboto_48_bold.c"
    "font/roboto_64_bold.c"
    "font/roboto_96_bold.c"
    "font/symbol_nerdfont.c"
    "font/symbol_nerdfont_48.c"
    "font/symbol_nerdfont_14.c"
    "font/symbol_nerdfont_24.c"
    "font/symbol_nerdfont_96.c"
    "img/logo.c"
    "lvgl_utils/screen_manager.c"

    INCLUDE_DIRS 
    "include"

    REQUIRES
    lvgl
    EPD
    touch_gt911
    filesystem_interface
    json
    HTTPS_request
    wifi
    widgets
)
